# creats a 1 pod deployment for the cluster-health-analyzer
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cluster-health-analyzer-mcp
  name: cluster-health-analyzer-mcp
  namespace: openshift-cluster-observability-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cluster-health-analyzer-mcp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cluster-health-analyzer-mcp
    spec:
      serviceAccountName: cluster-health-analyzer-mcp-thanos-querier
      automountServiceAccountToken: true
      containers:
      - name: cluster-health-mcp-server
        image: "quay.io/rh-ee-criolo/cluster-health-analyzer:mcp-pagination-mock"
        imagePullPolicy: Always
        args:
          - mcp
          - --mock-prefix-path
          - /var/cha
        env:
          - name: PROM_URL
            value: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091/"
          - name: ALERTMANAGER_URL
            value: "https://alertmanager-main.openshift-monitoring.svc.cluster.local:9094"
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 8085
          name: mcp
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: instructions
          mountPath: /etc/cha-instructions
          readOnly: true
      volumes:
      - name: instructions
        configMap:
          name: cluster-health-analyzer-mcp-instructions
